### ISSUE TITLE
Concerns about more baselines

### ISSUE THREAD

**Issue by Doragd** [chengzhipanpan/PaSeR#1]
Hi, I'm Gordon Lee.
Thanks for your excellent work on sentence representation learning (SRL).
I am working on collecting the SRL paper list with the unsupervised STS leaderboard.
https://github.com/Doragd/Awesome-Sentence-Embedding/
From the paper, I have seen its more powerful performance than SimCSE.
How about other previous contrastive methods for SRL, such as MoCoCSE, DCLR, PCL, ArcCSE, VaSCL, etc?
Are there any concerns that choosing the SimCSE as the baseline rather than others listed above?

**Comment by chengzhipanpan** [comment]
Hi, we choose SimCSE because it is very representative in contrastive methods. Our proposed PaSeR may not outperform more recent contrastive methods, but we aim to bring up a new generative perspective of SRL.

**Comment by Doragd** [comment]
Thanks for your reply
